//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUpSchoolProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCrt
    {
        public int CrtID { get; set; }
        public string CrtName { get; set; }
        public string CrtDescription { get; set; }
        public Nullable<System.DateTime> CrtDate { get; set; }
        public string Image { get; set; }
    }
}
