//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUpSchoolProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReference
    {
        public int ReferenceID { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceMail { get; set; }
        public string ReferencePhone { get; set; }
        public string ReferenceCompany { get; set; }
        public string ImageUrl3 { get; set; }
    }
}
